#!/bin/bash
##This script was created 081214kw
#Purpose: make a firewall using iptables

#remove ufw
#apt-get remove --purge ufw

#clear iptables
iptables -F

#Change input, forward and output policy
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

#open for input from loopback interface
iptables -A INPUT -s 127.0.0.1/32 -j ACCEPT

##open for input from home network
##only adresses 192.168.254.x 
#iptables -A INPUT -s 192.168.254.96/28 -p tcp --dport 22 -j ACCEPT

#open for input from answers 
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

##open for forward from home network
##only adresses 192.168.254.x 
#iptables -A FORWARD -s 192.168.254.96/28 -p tcp --dport 22 -j ACCEPT

##open for forward from answers 
#iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

#save the firewall
#(se også "/etc/network/interfaces")
iptables-save > /etc/iptables/rules

#udskriv firewall konfigurationen
iptables -L

