#!/bin/bash

#kommando: vpc N
# "N" er et tal mellem 0 og 99
 
# præmis: image-filen eksisterer i /home/klaus/.qemu/vm/vmN.qcow2"

#output:
# 1) vm$1 starter op

#sidste tal i mac-adressen genereres ud fra vm-nummeret
mac=$(printf "%02d" $1)

#devices opsættes
modprobe -v kvm
modprobe -v kvm_intel


#vmN startes op med "ubuntu-master"-mac adresse
qemu-system-x86_64 /home/klaus/.qemu/vm/vm$1.qcow2 \
  -enable-kvm \
  -m 512 \
  -name vm$1 \
  -net nic,model=virtio \
  -net user &

##vmN startes op med "vmN"-mac adresse
#qemu-system-x86_64 /home/klaus/.qemu/vm/vm$1.qcow2 \
#  -enable-kvm \
#  -m 512 \
#  -name vm$1 \
#  -net nic,model=virtio,macaddr=52:54:00:12:34:$mac \
#  -net user &
